CREATE TABLE ROOM (
    ID NUMBER,
    CONSTRAINT ROOM_PK PRIMARY KEY(ID),
    NUMBER_OF_GUESTS NUMBER NOT NULL,
    CHECK (NUMBER_OF_GUESTS >= 1),
    PRICE NUMBER(*, 2),
    BREAKFAST_INCLUDED NUMBER(1) DEFAULT 0,
    CHECK (BREAKFAST_INCLUDED BETWEEN 0 AND 1),
    PETS_ALLOWED NUMBER(1) DEFAULT 0,
    CHECK (PETS_ALLOWED BETWEEN 0 AND 1),
    DATE_AVAILABLE_FROM TIMESTAMP,
    HOTEL_ID NUMBER NOT NULL,
    CONSTRAINT HOTEL_FK FOREIGN KEY(HOTEL_ID) REFERENCES HOTEL(ID)
);