CREATE TABLE ORDERS (
    ID NUMBER,
    CONSTRAINT ORDERS_PK PRIMARY KEY(ID),
    USER_ID NUMBER NOT NULL,
    CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    ROOM_ID NUMBER NOT NULL,
    CONSTRAINT ROOM_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ID),
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID NUMBER(*, 2)
);